package com.example.shopping.dao;

import com.example.shopping.pojo.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ych_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    /*查询用户是否存在*/
    int selectByUsername(String username);
    /*根据用户名和密码查询用户信息*/
    User selectUserByUsernameAndPassword(@Param("username") String username, @Param("password")String password);
}